install.packages("glasso")
install.packages(c("huge", "expm", "rTensor", "igraph"))
install.packages("C://Users//sudhi//Desktop//Coordinatewise Gaussianization//replication//Model 1//Tlasso_1.0.2.tar.gz", repos = NULL, type = "source")
install.packages("tensr")
install.packages("expm")
install.packages("rTensor")
install.packages("doParallel")
install.packages("mvtnorm")
install.packages("purrr")
install.packages("furrr")